### ISSUE TITLE
Error after first usage of dropdown after app has loaded: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by dennismende** [cibernox/ember-basic-dropdown#296] opened 2017-05-10 14:33 UTC
Currently we get errors during each interaction with the web app after we used a dropdown once.
Error: `Cannot read property 'contains' of null`

We found out that it only happens after the production build process with ember-cli and when we remove `ember-cli-uglify` then everything works fine in production. Currently we are trying to reproduce the issue in a fresh app.

**Comment by cibernox** [comment] 2017-05-10 14:35
Interesting. If you get more information let me know to what part of the code exactly this belongs. It's pretty weird that uglify is breaking stuff.

**Comment by matthewconstantine** [comment] 2017-05-17 01:23
We're getting this error a lot in production. But it's quite intermittent. I had a full backtrace earlier but now can't reproduce it and have since lost the backtrace. In any case, it's this line that's reporting the error:

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L187

Specifically `this.dropdownElement.contains(e.target)` is failing. I think maybe the `dropdownId` used in [line 140](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L140) no longer exists in the DOM in some cases. I couldn't get any further than that but will provide more details if I can reproduce it again.

We're using it via ember-power-select-with-fallback v0.2.3 on ember 2.4.5.

**Comment by cibernox** [comment] 2017-11-23 14:37
Closing. Please, reopen if this bug is still present in the latest version.

**Closed by cibernox** 2017-11-23 14:37 UTC

**Comment by Luiz-N** [comment] 2018-04-10 04:59
@cibernox 
I'm getting this error in a non-prod build on every subsequent click after a dropdown goes away.

The stacktrace points to the `handleRootMouseDown` method & it seems to throw the error when trying to call `.contains` on `this.dropdownElement` which is null after the dropdown goes away.

I'm using the latest version of ember paper which is pulling in this addon and on Ember V 2.15.3

**Comment by cibernox** [comment] 2018-04-10 12:04
@Luiz-N can you check what version of ember-power-select is used underneath ember-paper?

**Comment by Luiz-N** [comment] 2018-04-10 14:38
Their latest package.json shows:

`"ember-power-select": "^1.8.5 || ^2.0.0-beta.2"`

**Comment by Luiz-N** [comment] 2018-05-15 15:06
My issue ended up being a weird dependency order issue between raven.js and rollbar that was messing with native mouse events.... All is good now. Thanks for checking!
